name: Build IdentityServer and WebApi

on:
  workflow_dispatch:

jobs:

  build-identity-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      working-directory: ./src/IdentityServer
      run: docker build . --file Dockerfile --tag jvannor/est-identity-server:latest
    - name: Login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Push
      run: docker push jvannor/est-identity-server:latest
    - name: Logout
      run: docker logout
    
  build-webp-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      working-directory: ./src/WebApi
      run: docker build . --file Dockerfile --tag jvannor/est-web-api:latest
    - name: Login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Push
      run: docker push jvannor/est-web-api:latest
    - name: Logout
      run: docker logout
